language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

sudo: required

services:
  - docker

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop

install:
  - docker version
  - docker-compose --version
  
script:
  - sudo docker-compose up -d
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/plugins/SDN/ODL/tests/test_generic_odl_plugin.py:GenericOpenDayLightTestCaseSuccess.test_add_a_list_of_acls_in_one_request
  
after_failure:
  - docker exec -it ovs1 ovs-vsctl show
  - docker exec -it ovs1 ovs-vsctl -v add-br br1
  - docker exec -it ovs2 ovs-vsctl show
  - docker exec -it ovs2 ovs-vsctl -v add-br br1
  - docker exec -it ovs3 ovs-vsctl show
  - docker exec -it ovs3 ovs-vsctl -v add-br br1
  - docker logs netapi_app
  - docker logs netapi_db
