language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

env:
  - TESTFOLDERS='networkapi/ACLS/ networkapi/acl/ networkapi/ambiente/ networkapi/api_deploy/ networkapi/api_environment/ networkapi/api_environment_vip/ networkapi/api_equipment/ networkapi/api_filter/ networkapi/api_group/ networkapi/api_healthcheck/ networkapi/api_interface/'
  - TESTFOLDERS='networkapi/api_ip/ networkapi/api_network/ networkapi/api_ogp/ networkapi/api_pools/ networkapi/api_rack/ networkapi/api_rest/ networkapi/api_task/ networkapi/api_usuario/ networkapi/api_vip_request/ networkapi/api_vlan/ networkapi/api_vrf/'
  - TESTFOLDERS='networkapi/auth/ networkapi/block rules/ networkapi/check/ networkapi/config/ networkapi/config_templates/ networkapi/distributedlock/ networkapi/equipamento/ networkapi/eventlog/ networkapi/extra_logging/ networkapi/filter/ networkapi/filterequiptype/'
  - TESTFOLDERS='networkapi/generated_config/ networkapi/grupo/ networkapi/grupovirtual/ networkapi/healthcheckexpect/ networkapi/infrastructure/ networkapi/interface/ networkapi/ip/ networkapi/models/ networkapi/plugins/ networkapi/queue_tools/ networkapi/rack/'
  - TESTFOLDERS='networkapi/requisicaovips/ networkapi/roteiro/ networkapi/semaforo/ networkapi/snippets/ networkapi/system/ networkapi/templates/ networkapi/test/ networkapi/tipoacesso/ networkapi/usuario/ networkapi/util/ networkapi/vlan/'

sudo: required

dist: trusty

services:
  - docker

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop

script:
  - docker network create globonetworkapi_netapi_net
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - sudo docker-compose up -d
  - sleep 5
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh $TESTFOLDER
  
after_failure:
  - docker exec ovs1 ovs-vsctl show
  - docker ps --all
  - docker exec netapi_app tail /tmp/networkapi.log
  - ping netapi_odl -c 1
