language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

env:
  - TESTFOLDERS='api_network'
  - TESTFOLDERS='api_pools'
  - TESTFOLDERS='plugins'
  - TESTFOLDERS='api_environment_vip api_equipment api_ip'
  - TESTFOLDERS='api_environment api_rack api_vip_request api_vlan equipamento requisicaovips system usuario'

sudo: required

dist: trusty

services:
  - docker

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop

script:
  - docker network create globonetworkapi_netapi_net
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - sudo docker-compose up -d
  - sleep 5
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/$TESTFOLDERS
  
after_failure:
  - docker exec ovs1 ovs-vsctl show
  - docker ps --all
  - docker exec netapi_app tail /tmp/networkapi.log
  - ping netapi_odl -c 1
