language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

sudo: required

dist: precise

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo apt-get update

install:
  #- curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - sleep 20
  - sudo docker-compose up -d
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/plugins/SDN/ODL/tests/test_generic_odl_plugin.py:GenericOpenDayLightTestCaseSuccess.test_add_a_list_of_acls_in_one_request
