language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo apt-get update
  # Docker
  - sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  

install:
  #- curl -sSL https://get.docker.com/ | sudo sh
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - sudo pip install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - sudo docker-compose up -d
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh networkapi/plugins/SDN/ODL/tests/test_generic_odl_plugin.py:GenericOpenDayLightTestCaseSuccess.test_add_a_list_of_acls_in_one_request
  
after_failure:
  - docker exec -it ovs1 ovs-vsctl show
  - docker exec -it ovs1 ovs-vsctl -v add-br br1
  - docker exec -it ovs2 ovs-vsctl show
  - docker exec -it ovs2 ovs-vsctl -v add-br br1
  - docker exec -it ovs3 ovs-vsctl show
  - docker exec -it ovs3 ovs-vsctl -v add-br br1
  - docker exec -it netapi_odl tail -100 /opt/opendaylight/data/log/karaf.log
