language: python

notifications:
  email: false

python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - develop_travis

env:
  - TESTFOLDER=networkapi/ACLS/
  - TESTFOLDER=networkapi/acl/
  - TESTFOLDER=networkapi/ambiente/
  - TESTFOLDER=networkapi/api_deploy/
  - TESTFOLDER=networkapi/api_environment/
  - TESTFOLDER=networkapi/api_environment_vip/
  - TESTFOLDER=networkapi/api_equipment/
  - TESTFOLDER=networkapi/api_filter/
  - TESTFOLDER=networkapi/api_group/
  - TESTFOLDER=networkapi/api_healthcheck/
  - TESTFOLDER=networkapi/api_interface/
  - TESTFOLDER=networkapi/api_ip/
  - TESTFOLDER=networkapi/api_network/
  - TESTFOLDER=networkapi/api_ogp/
  - TESTFOLDER=networkapi/api_pools/
  - TESTFOLDER=networkapi/api_rack/
  - TESTFOLDER=networkapi/api_rest/
  - TESTFOLDER=networkapi/api_task/
  - TESTFOLDER=networkapi/api_usuario/
  - TESTFOLDER=networkapi/api_vip_request/
  - TESTFOLDER=networkapi/api_vlan/
  - TESTFOLDER=networkapi/api_vrf/
  - TESTFOLDER=networkapi/auth/
  - TESTFOLDER=networkapi/blockrules/
  - TESTFOLDER=networkapi/check/
  - TESTFOLDER=networkapi/config/
  - TESTFOLDER=networkapi/config_templates/
  - TESTFOLDER=networkapi/distributedlock/
  - TESTFOLDER=networkapi/equipamento/
  - TESTFOLDER=networkapi/eventlog/
  - TESTFOLDER=networkapi/extra_logging/
  - TESTFOLDER=networkapi/filter/
  - TESTFOLDER=networkapi/filterequiptype/
  - TESTFOLDER=networkapi/generated_config/
  - TESTFOLDER=networkapi/grupo/
  - TESTFOLDER=networkapi/grupovirtual/
  - TESTFOLDER=networkapi/healthcheckexpect/
  - TESTFOLDER=networkapi/infrastructure/
  - TESTFOLDER=networkapi/interface/
  - TESTFOLDER=networkapi/ip/
  - TESTFOLDER=networkapi/models/
  - TESTFOLDER=networkapi/plugins/
  - TESTFOLDER=networkapi/queue_tools/
  - TESTFOLDER=networkapi/rack/
  - TESTFOLDER=networkapi/requisicaovips/
  - TESTFOLDER=networkapi/roteiro/
  - TESTFOLDER=networkapi/semaforo/
  - TESTFOLDER=networkapi/snippets/
  - TESTFOLDER=networkapi/system/
  - TESTFOLDER=networkapi/templates/
  - TESTFOLDER=networkapi/test/
  - TESTFOLDER=networkapi/tipoacesso/
  - TESTFOLDER=networkapi/usuario/
  - TESTFOLDER=networkapi/util/
  - TESTFOLDER=networkapi/vlan/

sudo: required

dist: trusty

services:
  - docker

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop

script:
  - docker network create globonetworkapi_netapi_net
  - sudo docker-compose --file scripts/travis/docker-compose-sdn-travis.yml up -d
  - sudo docker-compose up -d
  - sleep 5
  - docker ps --all
  - ./scripts/travis/wait_for_containers.sh
  - docker exec -it netapi_app ./scripts/travis/test_runner.sh $TESTFOLDER
  
after_failure:
  - docker exec ovs1 ovs-vsctl show
  - docker ps --all
  - docker exec netapi_app tail /tmp/networkapi.log
  - ping netapi_odl -c 1
